# Generated by Django 3.0.5 on 2020-07-14 19:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.SmallIntegerField(blank=True, choices=[('male', 1), ('female', 2)], null=True),
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('by', 'to')},
        ),
    ]
